apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: huston-housing-backend-pdb
  namespace: production
  labels:
    app: huston-housing-backend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: huston-housing-backend
  unhealthyPodEvictionPolicy: AlwaysAllow
